/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as TodosNewImport } from './routes/todos/new'
import { Route as TodosTodoIdEditImport } from './routes/todos/$todoId/edit'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const TodosNewRoute = TodosNewImport.update({
  id: '/todos/new',
  path: '/todos/new',
  getParentRoute: () => rootRoute,
} as any)

const TodosTodoIdEditRoute = TodosTodoIdEditImport.update({
  id: '/todos/$todoId/edit',
  path: '/todos/$todoId/edit',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/todos/new': {
      id: '/todos/new'
      path: '/todos/new'
      fullPath: '/todos/new'
      preLoaderRoute: typeof TodosNewImport
      parentRoute: typeof rootRoute
    }
    '/todos/$todoId/edit': {
      id: '/todos/$todoId/edit'
      path: '/todos/$todoId/edit'
      fullPath: '/todos/$todoId/edit'
      preLoaderRoute: typeof TodosTodoIdEditImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/todos/new': typeof TodosNewRoute
  '/todos/$todoId/edit': typeof TodosTodoIdEditRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/todos/new': typeof TodosNewRoute
  '/todos/$todoId/edit': typeof TodosTodoIdEditRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/todos/new': typeof TodosNewRoute
  '/todos/$todoId/edit': typeof TodosTodoIdEditRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/todos/new' | '/todos/$todoId/edit'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/todos/new' | '/todos/$todoId/edit'
  id: '__root__' | '/' | '/todos/new' | '/todos/$todoId/edit'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TodosNewRoute: typeof TodosNewRoute
  TodosTodoIdEditRoute: typeof TodosTodoIdEditRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TodosNewRoute: TodosNewRoute,
  TodosTodoIdEditRoute: TodosTodoIdEditRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/todos/new",
        "/todos/$todoId/edit"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/todos/new": {
      "filePath": "todos/new.tsx"
    },
    "/todos/$todoId/edit": {
      "filePath": "todos/$todoId/edit.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
