name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: ['23.x']

    steps:
      - uses: actions/checkout@v4
      - name: Use PNPM 10.11.0
        uses: pnpm/action-setup@v4.1.0
        with:
          version: 10.11.0
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node_version }}
          cache: 'pnpm'
      - name: pnpm install
        run: pnpm install
      - name: pnpm build
        run: pnpm build
      
